# Generated by Django 2.2.2 on 2019-07-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190326_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Agree'), (2, 'Neither Agree Nor Disagree'), (3, 'Disagree')], default=2),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('question', 'survey', 'choice')},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
    ]
