# Generated by Django 2.1.7 on 2020-01-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='cookie_name',
            field=models.CharField(help_text="Should start 'lcosvy_'", max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
